name: Production Deployment
on:
  push:
    branches: [ titsDeploy ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Deploy to remote server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          script: |
            cd ~/home/danielwetan/apps/node1
            git pull origin titsDeploy
            npm install --only=prod
            pm2 restart node1