name: Production Deployment
on:
  push:
    branches: [ titsDeploy ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Deploy to remote server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ vars.DO_HOST }}
          username: ${{ secrets.DO_USERNAME }}
          key: ${{ secrets.DO_PASSWORD }}
          script: |
            cd ${{ vars.DO_APP_PATH }}
            git pull origin titsDeploy
            npm install --only=prod
            pm2 restart node1