name: Production Deployment
on:
  push:
    branches: [ titsDeploy ]
jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: Deploy app to Development Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ vars.DO_HOST }}
          username: ${{ secrets.DO_USERNAME }}
          password: ${{ secrets.DO_PASSWORD }}
          sync: true
          script: |
            set -e
            echo "Deploying application ..."
            cd ${{ vars.DO_APP_PATH }}
            git fetch
            git switch titsDeploy
            git checkout .
            git pull origin titsDeploy --force
            npm install
            npm run build
            echo "Application deployed successfully!"
